[[actions]]
name = "play"
platform = "windows"
path = "MegaMerge/MegaMerge.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "MegaMerge/MegaMerge"
args = ["--launched-through-itch"]
